Booking/Booking.Web/ViewModels/AdminPanel/AdminPanelViewModel.cs
using System;
using System.Collections.Generic;
using Booking.Models.EfModels;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class AdminPanelViewModel
    {
        public IDictionary<Guid, string> AudienceMaps { get; set; }

        public Guid ActiveMapId { get; set; }

        public IEnumerable<BookingScheduleRule> ScheduleRules { get; set; }
    }
}

Booking/Booking.Web/ViewModels/AdminPanel/AudienceMapViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class AudienceMapViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string ImageUrl { get; set; }

        public IEnumerable<UiAudienceViewModel> Audiences { get; set; }
    }
}

Booking/Booking.Web/ViewModels/AdminPanel/CreateAudienceViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class CreateAudienceViewModel
    {
        [Required]
        public Guid AudienceMapId { get; set; }

        [Required]
        public string Name { get; set; }

        public HttpPostedFileBase RouteImage { get; set; }

        public HttpPostedFileBase LineDetailsImage { get; set; }
        
        [Required]
        public bool IsBookingAvailable { get; set; }

        [Required]
        public int Left { get; set; }

        [Required]
        public int Top { get; set; }

        [Required]
        public int Width { get; set; }

        [Required]
        public int Height { get; set; }

        [Required]
        public int SeatsCount { get; set; }

        [Required]
        public int BoardsCount { get; set; }

        [Required]
        public int LaptopsCount { get; set; }

        [Required]
        public int PrintersCount { get; set; }

        [Required]
        public int ProjectorsCount { get; set; }
    }
}

Booking/Booking.Web/ViewModels/AdminPanel/CreateScheduleRuleViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class CreateScheduleRuleViewModel
    {
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime AppliedDate { get; set; }

        public bool ForSunday { get; set; }

        public bool ForMonday { get; set; }

        public bool ForTuesday { get; set; }

        public bool ForWednesday { get; set; }

        public bool ForThursday { get; set; }

        public bool ForFriday { get; set; }

        public bool ForSaturday { get; set; }

        [Range(0, 24)]
        public int StartHour { get; set; }

        [Range(0, 24)]
        public int EndHour { get; set; }
    }
}

Booking/Booking.Web/ViewModels/AdminPanel/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class IndexViewModel
    {
    }
}

Booking/Booking.Web/ViewModels/AdminPanel/NewAudienceMapViewModel.cs
using System.Web;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class NewAudienceMapViewModel
    {
        public string Name { get; set; }

        public HttpPostedFileBase Image { get; set; }
    }
}

Booking/Booking.Web/ViewModels/AdminPanel/UiAudienceViewModel.cs
using System;

namespace Booking.Web.ViewModels.AdminPanel
{
    public class UiAudienceViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }

        public string Style { get; set; }

        public bool IsBookingAvailable { get; set; }
    }
}

Booking/Booking.Web/ViewModels/AudienceMap/AudienceMapViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Booking.Web.ViewModels.Audience;

namespace Booking.Web.ViewModels.AudienceMap
{
    public class AudienceMapViewModel
    {
        [Required]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string ImageUrl { get; set; }

        public IEnumerable<UiAudienceViewModel> Audiences { get; set; }
    }
}

Booking/Booking.Web/Controllers/AdminPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Booking.Models.EfModels;
using Booking.Repositories;
using Booking.Repositories.Interfaces;
using Booking.Repositories.Repositories;
using Booking.Services.Interfaces;
using Booking.Services.Services;
using Booking.Web.Helpers;
using Booking.Web.ViewModels.AdminPanel;
using Booking.Web.ViewModels.Audience;
using Booking.Web.ViewModels.AudienceMap;

namespace Booking.Web.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly IAudienceMapService _audienceMapService;
        private readonly IAudienceService _audienceService;
        private readonly IBookingScheduleRuleService _scheduleRuleService;
        private readonly IImageRepository _imageRepository = new ImageBlobRepository();

        public AdminPanelController()
        {
            var uof = new UnitOfWork();
            _audienceMapService = new AudienceMapService(uof);
            _audienceService = new AudienceService(uof);
            _scheduleRuleService = new BookingScheduleRuleService(uof);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var vm = new AdminPanelViewModel
            {
                ActiveMapId = AudienceMapSelector.AudienceMapId,
                AudienceMaps = _audienceMapService.GetAllAudienceMaps().ToDictionary(x => x.Id, x => x.Name),
                ScheduleRules = _scheduleRuleService.GetAllBookingScheduleRules()
            };

            return View(vm);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAudienceMapPage()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> CreateAudienceMap(NewAudienceMapViewModel vm)
        {
            var model = new AudienceMap
            {
                Name = vm.Name,
                ImageName = vm.Image.FileName
            };

            await _imageRepository.UploadImageAsync(vm.Image.InputStream, vm.Image.FileName);
            model.ImageName = vm.Image.FileName;

            _audienceMapService.CreateAudienceMap(model);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteAudienceMap(Guid id)
        {
            var audienceMap = _audienceMapService.GetAudienceMap(id);
            _audienceMapService.DeleteAudienceMap(audienceMap);
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult AudienceMap(Guid id)
        {
            var audienceMap = _audienceMapService.GetAudienceMap(id);
            var vm = new AudienceMapViewModel
            {
                Id = audienceMap.Id,
                ImageUrl = _imageRepository.GetImageUri(audienceMap.ImageName),
                Name = audienceMap.Name,
                Audiences = audienceMap.Audiences.Select(x => new UiAudienceViewModel
                {
                    Name = x.Name,
                    Style = _audienceService.GetStyleString(x),
                    IsBookingAvailable = x.IsBookingAvailable,
                    Id = x.Id
                })
            };

            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAudience(CreateAudienceViewModel vm)
        {
            var model = new Audience
            {
                Name = vm.Name,
                AudienceMapId = vm.AudienceMapId,
                IsBookingAvailable = vm.IsBookingAvailable,
                Left = vm.Left,
                Top = vm.Top,
                Width = vm.Width,
                Height = vm.Height,
                SeatsCount = vm.SeatsCount,
                BoardsCount = vm.BoardsCount,
                LaptopsCount = vm.LaptopsCount,
                PrintersCount = vm.PrintersCount,
                ProjectorsCount = vm.ProjectorsCount
            };

            if (vm.LineDetailsImage != null)
            {
                var fileName = vm.AudienceMapId + vm.LineDetailsImage.FileName;
                _imageRepository.UploadImage(vm.LineDetailsImage.InputStream, fileName);
                model.LineDetailsImageName = fileName;
            }
            if (vm.RouteImage != null)
            {
                var fileName = vm.AudienceMapId + vm.RouteImage.FileName;
                _imageRepository.UploadImage(vm.RouteImage.InputStream, fileName);
                model.RouteImageName = fileName;
            }


            _audienceService.CreateAudience(model);

            return RedirectToAction("AudienceMap", new {id = vm.AudienceMapId});
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAudience(Guid id, Guid audienceMapId)
        {
            _audienceService.DeleteAudienceById(id);
            return RedirectToAction("AudienceMap", new {id = audienceMapId});
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult SetActiveAudienceMap(Guid id)
        {
            AudienceMapSelector.AudienceMapId = id;
            return RedirectToAction("Index");
        }


        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult CreateScheduleRule(CreateScheduleRuleViewModel vm)
        {
            var daysOfWeek = new List<DayOfWeek>();
            if (vm.ForSunday) daysOfWeek.Add(DayOfWeek.Sunday);
            if (vm.ForMonday) daysOfWeek.Add(DayOfWeek.Monday);
            if (vm.ForTuesday) daysOfWeek.Add(DayOfWeek.Tuesday);
            if (vm.ForWednesday) daysOfWeek.Add(DayOfWeek.Wednesday);
            if (vm.ForThursday) daysOfWeek.Add(DayOfWeek.Thursday);
            if (vm.ForFriday) daysOfWeek.Add(DayOfWeek.Friday);
            if (vm.ForSaturday) daysOfWeek.Add(DayOfWeek.Saturday);

            foreach (var dayOfWeek in daysOfWeek)
            {
                var rule = new BookingScheduleRule
                {
                    AppliedDate = vm.AppliedDate,
                    DayOfWeek = dayOfWeek,
                    EndHour = vm.EndHour,
                    StartHour = vm.StartHour
                };

                _scheduleRuleService.CreateRule(rule);
            }

            return RedirectToAction("Index");
        }
    }
}

Booking/Booking.Web/Views/AdminPanel/AudienceMap.cshtml
@using Booking.Web.ViewModels.AdminPanel
@model Booking.Web.ViewModels.AudienceMap.AudienceMapViewModel

@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("//code.jquery.com/ui/1.12.1/jquery-ui.js")
    @Scripts.Render("~/Scripts/project/admin_panel/audience_map.js")
}
@section styles {
    <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css">
    @Styles.Render("~/Content/admin_panel/audience_map.css")
    @Styles.Render("~/Content/room-styles.css")
}


<div id="map-container">
    @foreach (var audience in Model.Audiences)
    {
        <div style="@audience.Style" class="room @(audience.IsBookingAvailable ? "room-available" : "room-not-available")">
            <div class="room-title">
                @audience.Name
            </div>
        </div>
    }

    <img id="map-image" src="@Model.ImageUrl"/>
</div>

<button id="new-audience-btn" class="btn btn-default">New audience</button>

<div>
    @foreach (var audience in Model.Audiences)
    {
        <div class="form-group">
            <span>@audience.Name</span>
            @using (Html.BeginForm("DeleteAudience", "AdminPanel", new {id = audience.Id, audienceMapId = Model.Id}))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-danger">Delete</button>
            }
        </div>
    }
</div>

@Html.Partial("_NewAudienceForm", new CreateAudienceViewModel {AudienceMapId = Model.Id})

Booking/Booking.Web/Views/AdminPanel/CreateAudienceMapPage.cshtml
@model Booking.Web.ViewModels.AdminPanel.NewAudienceMapViewModel

@using (Html.BeginForm("CreateAudienceMap", "AdminPanel", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    @Html.TextBoxFor(m => m.Name)

    @Html.LabelFor(x => x.Image)
    @Html.TextBoxFor(x => x.Image, new {type = "file"})
    @Html.ValidationMessageFor(x => x.Image)
    <button type="submit">Upload</button>
}

Booking/Booking.Web/Views/AdminPanel/Index.cshtml
@using Booking.Web.ViewModels.AdminPanel
@model Booking.Web.ViewModels.AdminPanel.AdminPanelViewModel

@section scripts{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/Scripts/bootstrap-datepicker/js/bootstrap-datepicker.js")

    <script>
        $(document)
            .ready(function() {

                var dp = $("#datepicker");

                dp.datepicker({
                    format: 'dd/MM/yyyy'
                });

                dp.on('changeDate',
                    function(ev) {
                        dp.val(ev.target.value);
                    });

            });
    </script>
}
@section styles {
    @Styles.Render("~/Content/bootstrap-datepicker.css")
}

<h2>Audience maps</h2>

<ul>
    @foreach (var pair in Model.AudienceMaps)
    {
        <li>
            <a href="@Url.Action("AudienceMap", "AdminPanel", new {id = pair.Key})">@pair.Value</a>

            @if (Model.ActiveMapId != pair.Key)
            {
                using (Html.BeginForm("SetActiveAudienceMap", "AdminPanel", new {id = pair.Key}, FormMethod.Post, new {@class = "inline-form"}))
                {
                    @Html.AntiForgeryToken()
                    <button type="submit" class="btn btn-primary">Set active</button>
                }
            }
            else
            {
                <label class="label label-success">active</label>
            }

            @using (Html.BeginForm("DeleteAudienceMap", "AdminPanel", new {id = pair.Key}, FormMethod.Post, new {@class = "inline-form"}))
            {
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-danger">Delete</button>
            }
        </li>
    }
</ul>


<a href="@Url.Action("CreateAudienceMapPage", "AdminPanel")">Create new audience map</a>

<br/>

<h2>Schedule rules</h2>

<ul>
    @foreach (var rule in Model.ScheduleRules)
    {
        <li>
            @rule.DayOfWeek (@rule.StartHour:00 - @rule.EndHour:00) - Applied on @rule.AppliedDate
        </li>
    }
</ul>

<br/>

@Html.Partial("_NewScheduleRulePartial", new CreateScheduleRuleViewModel {AppliedDate = DateTime.Now})

Booking/Booking.Web/Views/AdminPanel/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/admin_panel/layout.css")
    @Styles.Render("~/Content/bootstrap.min.css")
    @RenderSection("styles", required: false)
</head>
<body>
<div class="page-container">
    @RenderBody()
    @RenderSection("scripts", required: false)
</div>
</body>
</html>

Booking/Booking.Web/Views/AdminPanel/_NewAudienceForm.cshtml
@model Booking.Web.ViewModels.AdminPanel.CreateAudienceViewModel

<div>
    @using (Html.BeginForm("CreateAudience", "AdminPanel", FormMethod.Post, new {enctype = "multipart/form-data", id = "new-audience-form"}))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.IsBookingAvailable)
            @Html.CheckBoxFor(m => m.IsBookingAvailable)
        </div>

        @Html.HiddenFor(m => m.AudienceMapId)

        @Html.HiddenFor(m => m.Left)
        @Html.HiddenFor(m => m.Top)
        @Html.HiddenFor(m => m.Width)
        @Html.HiddenFor(m => m.Height)

        <div class="form-group">
            @Html.LabelFor(m => m.SeatsCount)
            @Html.EditorFor(m => m.SeatsCount)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.BoardsCount)
            @Html.EditorFor(m => m.BoardsCount)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LaptopsCount)
            @Html.EditorFor(m => m.LaptopsCount)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.PrintersCount)
            @Html.EditorFor(m => m.PrintersCount)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ProjectorsCount)
            @Html.EditorFor(m => m.ProjectorsCount)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.RouteImage)
            @Html.TextBoxFor(x => x.RouteImage, new {type = "file"})
            @Html.ValidationMessageFor(x => x.RouteImage)
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.LineDetailsImage)
            @Html.TextBoxFor(x => x.LineDetailsImage, new {type = "file"})
            @Html.ValidationMessageFor(x => x.LineDetailsImage)
        </div>

        <button type="submit" class="btn btn-primary">Upload</button>
    }
</div>

Booking/Booking.Web/Views/AdminPanel/_NewScheduleRulePartial.cshtml
@model Booking.Web.ViewModels.AdminPanel.CreateScheduleRuleViewModel

<h2>New schedule rule</h2>

@using (Html.BeginForm("CreateScheduleRule", "AdminPanel", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <p>
        Applied date:
        @Html.EditorFor(m => m.AppliedDate, new {htmlAttributes = new {id = "datepicker" } })
    </p>

    <div class="form-group">
        @Html.LabelFor(m => m.ForSunday)
        @Html.EditorFor(m => m.ForSunday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ForMonday)
        @Html.EditorFor(m => m.ForMonday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ForTuesday)
        @Html.EditorFor(m => m.ForTuesday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ForWednesday)
        @Html.EditorFor(m => m.ForWednesday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ForThursday)
        @Html.EditorFor(m => m.ForThursday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ForFriday)
        @Html.EditorFor(m => m.ForFriday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ForSaturday)
        @Html.EditorFor(m => m.ForSaturday)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.StartHour)
        @Html.EditorFor(m => m.StartHour)
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.EndHour)
        @Html.EditorFor(m => m.EndHour)
    </div>

    <button type="submit" class="btn btn-success">Create</button>
}