Booking/Booking.Web/ViewModels/Event/CreateEditEventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Booking.Web.ViewModels.Event
{
    public class CreateEditEventViewModel
    {
        public Guid Id { get; set; }

        public DateTime StartTime { get; set; }
        
        public DateTime EndTime { get; set; }

        [Required(ErrorMessageResourceType = typeof(Localization.Localization),
            ErrorMessageResourceName = "ValidationMessage_Required")]
        public string Title { get; set; }

        public string AdditionalInfo { get; set; }

        public bool IsAuthorShown { get; set; }

        public string AuthorName { get; set; }

        public bool IsJoinAvailable { get; set; }

        public bool IsPublic { get; set; }

        public IDictionary<Guid, string> AvailableAudiences { get; set; }

        public Guid AudienceId { get; set; }
    }
}

Booking/Booking.Web/ViewModels/Event/DisplayEventPopupViewModel.cs
using System;

namespace Booking.Web.ViewModels.Event
{
    public class DisplayEventPopupViewModel
    {
        public Guid Id { get; set; }

        public Guid AudienceId { get; set; }

        public string AudienceName { get; set; }

        public DateTime StartTime { get; set; }

        public string EventDate { get; set; }

        public string Title { get; set; }

        public string AdditionalInfo { get; set; }

        public int Duration { get; set; }

        public string AuthorName { get; set; }

        public bool IsJoinAvailable { get; set; }

        public bool CanEdit { get; set; }

        public int ParticipantsCount { get; set; }
    }
}

Booking/Booking.Web/ViewModels/Event/DisplayEventViewModel.cs
using System;
using System.Collections.Generic;
using Booking.Web.ViewModels.AudienceMap;

namespace Booking.Web.ViewModels.Event
{
    public class DisplayEventViewModel
    {
        public Guid Id { get; set; }

        public Guid AudienceId { get; set; }

        public string AudienceName { get; set; }

        public DateTime StartTime { get; set; }

        public int Duration { get; set; }

        public string Title { get; set; }

        public string AdditionalInfo { get; set; }

        public string AuthorName { get; set; }
        
        public bool IsJoinAvailable { get; set; }

        public bool CanEdit { get; set; }

        public IDictionary<Guid, string> ParticipantsEmails { get; set; }

        public AudienceMapViewModel AudienceMap { get; set; }
    }
}

Booking/Booking.Web/ViewModels/Event/EventEditViewModel.cs
using System;
using System.Collections.Generic;
using Booking.Web.ViewModels.AudienceMap;

namespace Booking.Web.ViewModels.Event
{
    public class EventEditViewModel : CreateEditEventViewModel
    {
        public IDictionary<Guid, string> ParticipantsEmails { get; set; }

        public AudienceMapViewModel AudienceMap { get; set; }
    }
}

Booking/Booking.Web/ViewModels/Event/JoinEventViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Booking.Web.ViewModels.Event
{
    public class JoinEventViewModel
    {
        [Required(ErrorMessageResourceType = typeof(Localization.Localization),
             ErrorMessageResourceName = "ValidationMessage_Required")]
        [EmailAddress(ErrorMessageResourceType = typeof(Localization.Localization),
             ErrorMessageResourceName = "RegisterViewModel_Email_ValidationMessage")]
        public string Email { get; set; }

        public Guid EventId { get; set; }

        public int ParticipantsCount { get; set; }

        public bool ParticipantsCountLabelHidden { get; set; }
    }
}

Booking/Booking.Web/Controllers/AudienceController.cs
using System;
using System.Web.Mvc;
using AutoMapper;
using Booking.Repositories;
using Booking.Services.Interfaces;
using Booking.Services.Services;
using Booking.Web.Helpers;
using Booking.Web.ViewModels.Audience;

namespace Booking.Web.Controllers
{
    [HandleException]
    public class AudienceController : Controller
    {
        private readonly IAudienceService _audienceService;

        public AudienceController()
        {
            var uof = new UnitOfWork();
            _audienceService = new AudienceService(uof);
        }

        [HttpGet]
        public ActionResult Index(Guid audienceId)
        {
            var model = _audienceService.GetAudience(audienceId);
            var vm = Mapper.Map<AudienceIndexViewModel>(model);
            return View(vm);
        }

        [HttpGet]
        public ActionResult GetAudienceInfo(Guid audienceId)
        {
            var audience = _audienceService.GetAudience(audienceId);
            var vm = Mapper.Map<AudienceInfoViewModel>(audience);

            return PartialView("_AudienceInfoPartial", vm);
        }

        [HttpGet]
        public ActionResult GetSchedule(Guid audienceId, DateTime startDate, DateTime endDate)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        public ActionResult IsFree(Guid audienceId, DateTime startEvent, DateTime endEvent, Guid? eventId)
        {
            var isFree = _audienceService.IsFree(audienceId, startEvent, endEvent, eventId);
            return Content(isFree.ToString());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Open(Guid audienceId)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Close(Guid audienceId)
        {
            throw new NotImplementedException();
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Guid audienceId)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Save(AudienceInfoViewModel audienceInfoViewModel)
        {
            throw new NotImplementedException();
        }
    }
}

Booking/Booking.Web/Controllers/EventController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Booking.Models.EfModels;
using Booking.Repositories;
using Booking.Services.Interfaces;
using Booking.Services.Services;
using Booking.Web.Helpers;
using Booking.Web.ViewModels.AudienceMap;
using Booking.Web.ViewModels.Event;
using Microsoft.AspNet.Identity;

namespace Booking.Web.Controllers
{
    [HandleException]
    public class EventController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IAudienceService _audienceService;
        private readonly IAudienceMapService _audienceMapService;

        public EventController()
        {
            var uof = new UnitOfWork();
            _audienceService = new AudienceService(uof);
            var usersService = new UsersService();
            var emailNotificationService = new EmailNotificationService();
            _eventService = new EventService(uof, usersService, emailNotificationService, _audienceService);
            _audienceMapService = new AudienceMapService(uof);
        }

        [HttpGet]
        public ActionResult DisplayEventPopup(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);
            var vm = Mapper.Map<Event, DisplayEventPopupViewModel>(eventEntity);
            vm.CanEdit = _eventService.CanEdit(User, eventEntity);

            return PartialView("_DisplayEventPopup", vm);
        }

        [HttpGet]
        public ActionResult Index(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);
            var vm = Mapper.Map<DisplayEventViewModel>(eventEntity);
            vm.CanEdit = _eventService.CanEdit(User, eventEntity);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Participate(JoinEventViewModel joinEventVm)
        {
            _eventService.AddParticipant(joinEventVm.Email, joinEventVm.EventId);
            return RedirectToAction("Index", new {eventId = joinEventVm.EventId});
        }

        [HttpGet]
        [Authorize]
        public ActionResult GetNewEventPopup()
        {
            var audiences = _audienceMapService.GetAudienceMap(AudienceMapSelector.AudienceMapId).Audiences;
            var availableAudiences = audiences.Where(a => a.IsBookingAvailable)
                .ToDictionary(a => a.Id, a => a.Name);

            var date = DateTime.Now.AddHours(2);
            var newMinute = (date.Minute/10)*10;
            date = date.AddMinutes(newMinute - date.Minute);

            var viewModel = new CreateEditEventViewModel
            {
                AvailableAudiences = availableAudiences,
                EndTime = date.AddMinutes(30),
                StartTime = date,
                IsPublic = true
            };

            return PartialView("_NewEventPartial", viewModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveParticipant(Guid participantId)
        {
            _eventService.RemoveParticipant(User, participantId);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);
            var vm = Mapper.Map<EventEditViewModel>(eventEntity);

            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(Guid audienceId, DateTime eventDateTime, int duration)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateEditEventViewModel vm)
        {
            var isFree = _audienceService.IsFree(vm.AudienceId, vm.StartTime, vm.EndTime, vm.Id);

            var duration = vm.EndTime.Subtract(vm.StartTime).TotalMinutes;

            if (duration < 20 || !isFree)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (vm.IsPublic && string.IsNullOrWhiteSpace(vm.Title))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Event newEvent = Mapper.Map<Event>(vm);
            newEvent.AuthorId = User.Identity.GetUserId();

            _eventService.CreateEvent(newEvent);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Cancel(Guid eventId)
        {
            _eventService.CancelEvent(User, eventId);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpGet]
        [Authorize]
        public ActionResult GetCancellationForm(Guid eventId)
        {
            return PartialView("_CancelEventPartial", eventId);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditPopup(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);

            var viewModel = Mapper.Map<CreateEditEventViewModel>(eventEntity);

            return PartialView("_EditEventPopupPartial", viewModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Save(EventEditViewModel vm)
        {
            TimeSpan span = vm.EndTime.Subtract(vm.StartTime);
            var duration = (int) span.TotalMinutes;

            var eventEntity = _eventService.GetEvent(vm.Id);

            if (!_audienceService.IsFree(vm.AudienceId, vm.StartTime, vm.EndTime, vm.Id) || duration < 20)
            {
                var model = _audienceMapService.GetAudienceMap(AudienceMapSelector.AudienceMapId);
                vm.AudienceMap = Mapper.Map<AudienceMapViewModel>(model);
                vm.ParticipantsEmails = eventEntity.EventParticipants.ToVmDictionary();
                return View("Edit", vm);
            }

            eventEntity.Title = vm.Title;
            eventEntity.AdditionalInfo = vm.AdditionalInfo;
            eventEntity.AudienceId = vm.AudienceId;
            eventEntity.AuthorName = vm.AuthorName;
            eventEntity.IsAuthorShown = vm.IsAuthorShown;
            eventEntity.IsJoinAvailable = vm.IsJoinAvailable;
            eventEntity.StartTime = vm.StartTime;
            eventEntity.EndTime = vm.EndTime;

            _eventService.UpdateEvent(User, eventEntity);

            return RedirectToAction("Index", new {eventId = eventEntity.Id});
        }

        [HttpPost]
        [Authorize]
        public ActionResult SaveFromPopup(CreateEditEventViewModel vm)
        {
            TimeSpan span = vm.EndTime.Subtract(vm.StartTime);
            var duration = (int) span.TotalMinutes;

            var eventEntity = _eventService.GetEvent(vm.Id);
            if (!_audienceService.IsFree(vm.AudienceId, vm.StartTime, vm.EndTime, vm.Id) || duration < 20)
            {
                var model = _audienceMapService.GetAudienceMap(AudienceMapSelector.AudienceMapId);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            eventEntity.Title = vm.Title;
            eventEntity.AdditionalInfo = vm.AdditionalInfo;
            eventEntity.AudienceId = vm.AudienceId;
            eventEntity.AuthorName = vm.AuthorName;
            eventEntity.IsAuthorShown = vm.IsAuthorShown;
            eventEntity.IsJoinAvailable = vm.IsJoinAvailable;
            eventEntity.StartTime = vm.StartTime;
            eventEntity.EndTime = vm.EndTime;

            _eventService.UpdateEvent(User, eventEntity);

            return RedirectToAction("DisplayEventPopup", new {eventId = eventEntity.Id});
        }
    }
}

Booking/Booking.Web/Views/Event/Edit.cshtml
@using Booking.Web.Localization
@model Booking.Web.ViewModels.Event.EventEditViewModel

@{
    ViewBag.Title = Model.Title;
}

@section styles{
    @Styles.Render("~/Content/room-styles.css")
    @Styles.Render("~/Content/home-page.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("http://fonts.googleapis.com/css?family=Nunito:400,300,700")
    @Styles.Render("~/Content/schedule.css")
    @Styles.Render("~/Content/event-page.css")
    @Styles.Render("~/Content/form-inputs.css")
}

@section scripts
{
    @Scripts.Render("//code.jquery.com/ui/1.12.1/jquery-ui.js")
    @Scripts.Render("~/Scripts/jquery.mapit.js")
    @Scripts.Render("~/Scripts/initializers.js")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/project/event-edit-page.js")
    @Scripts.Render("~/Scripts/project/room-map.js")
}


<input type="hidden" id="audience-is-free-url" value="@Url.Action("IsFree", "Audience")"/>
<input type="hidden" id="display-event-url" value="@Url.Action("Index", "Event")"/>

@foreach (var audience in Model.AudienceMap.Audiences)
{
    <input type="hidden" id="audience-@audience.Id-name" value="@audience.Name"/>
}

<div class="event-container">
    <div class="page-container container">
        @using (Html.BeginForm("Save", "Event"))
        {
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="col-md-8">
                    <div id="event-info">
                        @Html.HiddenFor(m => m.Id, new {id = "event-id"})

                        @Html.ValidationMessageFor(m => m.Title, "", new {@class = "validation-error"})
                        @Html.TextBoxFor(m => m.Title, new {@class = "text-input", id = "event-title-edit"})
                        <br/>

                        <input type="checkbox" id="is-author-shown" name="IsAuthorShown"  value="true" @(Model.IsAuthorShown ? "checked" : "") />
                        <label for="is-author-shown"><span></span>@Localization.ShowAuthor</label>
                        <input name="IsAuthorShown" type="hidden" value="false" /> 

                        <span>@Localization.Or</span>
                        @Html.TextBoxFor(m => m.AuthorName, new {@class = "text-input", placeholder = Localization.ShowOrganizer})
                        <br/>
                        @Html.TextAreaFor(m => m.AdditionalInfo, new {@class = "text-area", placeholder = Localization.AdditionalInformation})
                        <br/>

                        <input type="checkbox" id="is-join-available" name="IsJoinAvailable" value=true @(Model.IsJoinAvailable ? "checked" : "") />
                        <label for="is-join-available"><span></span>@Localization.JoinAvailable</label>
                        <input name="IsJoinAvailable" type="hidden" value="false" /> 

                        @if (Model.IsJoinAvailable)
                        {
                            <span>@string.Format(Localization.EventPageParticipantsCount, Model.ParticipantsEmails.Count)</span>
                        }
                    </div>
                </div>
                <div class="col-md-4">
                    <div id="event-calendar">
                        @Html.HiddenFor(m => m.StartTime, new {id = "start-date"})
                        @Html.HiddenFor(m => m.EndTime, new {id = "end-date"})
                        <div id="event-date" class="event-date-container">
                            <i class="fa fa-calendar" aria-hidden="true"></i>
                            <div class="datetime-updown-outer">
                                <div class="datetime-updown-control datetime-updown-day">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">18.</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                                <div class="datetime-updown-control datetime-updown-month">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">09.</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                                <div class="datetime-updown-control datetime-updown-year">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">16</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                            </div>

                            <i class="fa fa-clock-o" aria-hidden="true"></i>

                            <div class="datetime-updown-outer">
                                <div class="datetime-updown-control datetime-updown-start-hour">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">18:</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                                <div class="datetime-updown-control datetime-updown-start-minute">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">00</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                            </div>
                            <span>-</span>
                            <div class="datetime-updown-outer">
                                <div class="datetime-updown-control datetime-updown-end-hour">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">18:</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                                <div class="datetime-updown-control datetime-updown-end-minute">
                                    <i class="fa fa-caret-up" aria-hidden="true"></i>
                                    <span class="datetime-updown-label">30</span>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                </div>
                            </div>
                        </div>
                        <div class="icons-container">
                            <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>
                            <i class="fa fa-envelope-o" aria-hidden="true"></i>
                            <i class="fa fa-print" aria-hidden="true"></i>
                        </div>
                        <div id="edit-buttons-container">
                            <button id="btn-cancel" type="button">@Localization.Cancellation</button>
                            <input type="submit" id="btn-save-event" value="@Localization.Save">
                        </div>
                        <div class="audience-not-free-message">
                            <i class="fa fa-frown-o" aria-hidden="true"></i>
                            <div>@Localization.AudienceIsAlreadyBooked</div>
                        </div>
                    </div>
                </div>
            </div>
            @Html.HiddenFor(m => m.AudienceId, new {id = "chosen-audience-id"})
        }

        @if (Model.IsJoinAvailable && Model.ParticipantsEmails.Count > 0)
        {
            <div class="row">
                <div class="col-md-12">
                    <div class="participants-container">
                        <span>@Localization.RegisteredParticipants</span>
                        <ul>
                            @foreach (var pair in Model.ParticipantsEmails)
                            {
                                <li class="participant-email-li col-md-4">
                                    <span>@pair.Value</span>
                                    <i class="fa fa-times" aria-hidden="true" data-form-id="#remove-participant-@pair.Key"></i>
                                    @using (Html.BeginForm("RemoveParticipant", "Event", new {participantId = pair.Key}, FormMethod.Post, new {@class = "remove-participant-form"}))
                                    {
                                        @Html.AntiForgeryToken()
                                        <input type="submit" value="submit" id="remove-participant-@pair.Key" class="remove-participant-submit"/>
                                    }
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@Html.Partial("_RoomMapChoicePartial", Model)

<input type="hidden" id="redirect-to-home-url" value="@Url.Action("Index", "Home")"/>
<input type="hidden" id="redirect-to-audience-url" value="@Url.Action("Index", "Audience")"/>

<div class="buttons-container">
    <div class="page-container container">
        <div class="link-buttons">
            <div class="link-btn-container" id="redirect-audience-btn">
                <div class="btn-squares">
                    <div class="square"></div>
                    <div class="square"></div>
                    <div class="square"></div>
                    <div class="square square-red"></div>
                </div>
                <span>@Localization.AudienceSchedule <span id="audience-name"></span></span>
            </div>
            <div class="link-btn-container" id="redirect-home-btn">
                <div class="btn-squares">
                    <div class="square square-red"></div>
                    <div class="square square-red"></div>
                    <div class="square square-red"></div>
                    <div class="square square-red"></div>
                </div>
                <span>@Localization.AllAudiencesSchedule</span>
            </div>
        </div>
    </div>
</div>

<div id="map_canvas"></div>

Booking/Booking.Web/Views/Event/Index.cshtml
@using Booking.Web.Localization
@using Booking.Web.ViewModels.Event
@model Booking.Web.ViewModels.Event.DisplayEventViewModel

@{
    ViewBag.Title = Model.Title;
}

@section styles{
    @Styles.Render("~/Content/room-styles.css")
    @Styles.Render("~/Content/home-page.css")
    @Styles.Render("~/Content/event-popups.css")
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("http://fonts.googleapis.com/css?family=Nunito:400,300,700")
    @Styles.Render("~/Content/schedule.css")
    @Styles.Render("~/Content/event-page.css")
}

@section scripts
{
    @Scripts.Render("//code.jquery.com/ui/1.12.1/jquery-ui.js")
    @Scripts.Render("~/Scripts/jquery.mapit.js")
    @Scripts.Render("~/Scripts/initializers.js")
    @Scripts.Render("~/Scripts/project/event-page.js")
    @Scripts.Render("~/Scripts/project/cancel-event.js")
}


<input type="hidden" id="redirect-to-edit-event-url" value="@Url.Action("Edit", "Event", new {eventId = Model.Id})"/>

<div class="event-container">
    <div class="page-container container">
        <div class="row">
            <div class="col-md-8">
                <div id="event-info">
                    <div class="event-title">@Model.Title</div>
                    <br/>
                    @if (!string.IsNullOrEmpty(Model.AuthorName))
                    {
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span id="author-name">@Model.AuthorName</span>
                    }
                    <br/>
                    <p>@Model.AdditionalInfo</p>
                    <br/>
                    @if (Model.IsJoinAvailable)
                    {
                        @Html.Partial("_JoinEventPartial", new JoinEventViewModel {EventId = Model.Id, ParticipantsCount = Model.ParticipantsEmails.Count})
                    }
                </div>
            </div>
            <div class="col-md-4">
                <div id="event-calendar">
                    <div class="event-date-container">
                        <i class="fa fa-calendar" aria-hidden="true"></i>
                        <span>@Model.StartTime.ToString("dd.MM.yyyy")</span>
                        <i class="fa fa-clock-o" aria-hidden="true"></i>
                        <span>@Model.StartTime.ToString("HH:mm") - @Model.StartTime.AddMinutes(Model.Duration).ToString("HH:mm")</span>
                    </div>
                    <div class="icons-container">
                        <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>
                        <i class="fa fa-envelope-o" aria-hidden="true"></i>
                        <i class="fa fa-print" aria-hidden="true"></i>
                    </div>
                    @if (Model.CanEdit)
                    {
                        <div id="edit-buttons-container">
                            <button id="btn-edit-event">@Localization.Edit</button>
                            <button class="cancel-event-btn" id="btn-show-cancel-popup" data-eventId="@Model.Id" onclick="displayCancelEventPopup()" data-toggle="modal" data-target=".example-modal-sm">@Localization.Cancel</button>
                        </div>
                    }
                </div>
            </div>
        </div>
        @if (Model.IsJoinAvailable && Model.CanEdit && Model.ParticipantsEmails.Count > 0)
        {
            <div class="row">
                <div class="col-md-12">
                    <div class="participants-container">
                        <span>@Localization.RegisteredParticipants</span>
                        <ul>
                            @foreach (var pair in Model.ParticipantsEmails)
                            {
                                <li class="participant-email-li col-md-4">
                                    <span>@pair.Value</span>
                                    <i class="fa fa-times" aria-hidden="true" data-form-id="#remove-participant-@pair.Key"></i>
                                    @using (Html.BeginForm("RemoveParticipant", "Event", new {participantId = pair.Key}, FormMethod.Post, new {@class = "remove-participant-form"}))
                                    {
                                        @Html.AntiForgeryToken()
                                        <input type="submit" value="submit" id="remove-participant-@pair.Key" class="remove-participant-submit"/>
                                    }
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        }
    </div>

</div>

@Html.Partial("_RoomMapRoutePartial", Model)

<input type="hidden" id="redirect-to-home-url" value="@Url.Action("Index", "Home")"/>
<input type="hidden" id="redirect-to-audience-url" value="@Url.Action("Index", "Audience", new {audienceId = Model.AudienceId})"/>

<div class="buttons-container">
    <div class="page-container container">
        <div class="link-buttons">
            <div class="link-btn-container" id="redirect-audience-btn">
                <div class="btn-squares">
                    <div class="square"></div>
                    <div class="square"></div>
                    <div class="square"></div>
                    <div class="square square-red"></div>
                </div>
                <span>@Localization.AudienceSchedule @Model.AudienceName</span>
            </div>
            <div class="link-btn-container" id="redirect-home-btn">
                <div class="btn-squares">
                    <div class="square square-red"></div>
                    <div class="square square-red"></div>
                    <div class="square square-red"></div>
                    <div class="square square-red"></div>
                </div>
                <span>@Localization.AllAudiencesSchedule</span>
            </div>
        </div>
    </div>
</div>

<div id="map_canvas"></div>

Booking/Booking.Web/Views/Event/_CancelEventPartial.cshtml
@using Booking.Web.Localization
@model Guid

@using (Ajax.BeginForm("Cancel", "Event", new {eventId = @Model},
    new AjaxOptions
    {
        HttpMethod = "Post",
        OnSuccess = "closeCancelEventPopup"
    }))
{
    @Html.AntiForgeryToken()
    <div class="cancel-event-container">
        <div class="cancel-event-header">
            <i class="fa fa-ban icon-ban" aria-hidden="true"></i>
            <span class="cancel-event-ask-message">@Localization.CancelEventAskMessage</span>
        </div>
        <div class="btns-body-cancel-popup">
            <button class="close-this-popup" data-dismiss="modal">@Localization.No</button>
            <input type="submit" id="del-event" class="cancel-event-submit" data-id="@Model" value="@Localization.Yes"/>
        </div>
        <input type="hidden" id="delete-event-popup-url" value="@Url.Action("Cancel", "Event")"/>
    </div>
}