Booking/Booking.Web/ViewModels/Event/DisplayEventPopupViewModel.cs
using System;

namespace Booking.Web.ViewModels.Event
{
    public class DisplayEventPopupViewModel
    {
        public Guid Id { get; set; }

        public Guid AudienceId { get; set; }

        public string AudienceName { get; set; }

        public DateTime StartTime { get; set; }

        public string EventDate { get; set; }

        public string Title { get; set; }

        public string AdditionalInfo { get; set; }

        public int Duration { get; set; }

        public string AuthorName { get; set; }

        public bool IsJoinAvailable { get; set; }

        public bool CanEdit { get; set; }

        public int ParticipantsCount { get; set; }
    }
}

Booking/Booking.Web/Controllers/EventController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Booking.Models.EfModels;
using Booking.Repositories;
using Booking.Services.Interfaces;
using Booking.Services.Services;
using Booking.Web.Helpers;
using Booking.Web.ViewModels.AudienceMap;
using Booking.Web.ViewModels.Event;
using Microsoft.AspNet.Identity;

namespace Booking.Web.Controllers
{
    [HandleException]
    public class EventController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IAudienceService _audienceService;
        private readonly IAudienceMapService _audienceMapService;

        public EventController()
        {
            var uof = new UnitOfWork();
            _audienceService = new AudienceService(uof);
            var usersService = new UsersService();
            var emailNotificationService = new EmailNotificationService();
            _eventService = new EventService(uof, usersService, emailNotificationService, _audienceService);
            _audienceMapService = new AudienceMapService(uof);
        }

        [HttpGet]
        public ActionResult DisplayEventPopup(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);
            var vm = Mapper.Map<Event, DisplayEventPopupViewModel>(eventEntity);
            vm.CanEdit = _eventService.CanEdit(User, eventEntity);

            return PartialView("_DisplayEventPopup", vm);
        }

        [HttpGet]
        public ActionResult Index(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);
            var vm = Mapper.Map<DisplayEventViewModel>(eventEntity);
            vm.CanEdit = _eventService.CanEdit(User, eventEntity);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Participate(JoinEventViewModel joinEventVm)
        {
            _eventService.AddParticipant(joinEventVm.Email, joinEventVm.EventId);
            return RedirectToAction("Index", new {eventId = joinEventVm.EventId});
        }

        [HttpGet]
        [Authorize]
        public ActionResult GetNewEventPopup()
        {
            var audiences = _audienceMapService.GetAudienceMap(AudienceMapSelector.AudienceMapId).Audiences;
            var availableAudiences = audiences.Where(a => a.IsBookingAvailable)
                .ToDictionary(a => a.Id, a => a.Name);

            var date = DateTime.Now.AddHours(2);
            var newMinute = (date.Minute/10)*10;
            date = date.AddMinutes(newMinute - date.Minute);

            var viewModel = new CreateEditEventViewModel
            {
                AvailableAudiences = availableAudiences,
                EndTime = date.AddMinutes(30),
                StartTime = date,
                IsPublic = true
            };

            return PartialView("_NewEventPartial", viewModel);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveParticipant(Guid participantId)
        {
            _eventService.RemoveParticipant(User, participantId);
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);
            var vm = Mapper.Map<EventEditViewModel>(eventEntity);

            return View(vm);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create(Guid audienceId, DateTime eventDateTime, int duration)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateEditEventViewModel vm)
        {
            var isFree = _audienceService.IsFree(vm.AudienceId, vm.StartTime, vm.EndTime, vm.Id);

            var duration = vm.EndTime.Subtract(vm.StartTime).TotalMinutes;

            if (duration < 20 || !isFree)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (vm.IsPublic && string.IsNullOrWhiteSpace(vm.Title))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Event newEvent = Mapper.Map<Event>(vm);
            newEvent.AuthorId = User.Identity.GetUserId();

            _eventService.CreateEvent(newEvent);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Cancel(Guid eventId)
        {
            _eventService.CancelEvent(User, eventId);
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpGet]
        [Authorize]
        public ActionResult GetCancellationForm(Guid eventId)
        {
            return PartialView("_CancelEventPartial", eventId);
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditPopup(Guid eventId)
        {
            var eventEntity = _eventService.GetEvent(eventId);

            var viewModel = Mapper.Map<CreateEditEventViewModel>(eventEntity);

            return PartialView("_EditEventPopupPartial", viewModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Save(EventEditViewModel vm)
        {
            TimeSpan span = vm.EndTime.Subtract(vm.StartTime);
            var duration = (int) span.TotalMinutes;

            var eventEntity = _eventService.GetEvent(vm.Id);

            if (!_audienceService.IsFree(vm.AudienceId, vm.StartTime, vm.EndTime, vm.Id) || duration < 20)
            {
                var model = _audienceMapService.GetAudienceMap(AudienceMapSelector.AudienceMapId);
                vm.AudienceMap = Mapper.Map<AudienceMapViewModel>(model);
                vm.ParticipantsEmails = eventEntity.EventParticipants.ToVmDictionary();
                return View("Edit", vm);
            }

            eventEntity.Title = vm.Title;
            eventEntity.AdditionalInfo = vm.AdditionalInfo;
            eventEntity.AudienceId = vm.AudienceId;
            eventEntity.AuthorName = vm.AuthorName;
            eventEntity.IsAuthorShown = vm.IsAuthorShown;
            eventEntity.IsJoinAvailable = vm.IsJoinAvailable;
            eventEntity.StartTime = vm.StartTime;
            eventEntity.EndTime = vm.EndTime;

            _eventService.UpdateEvent(User, eventEntity);

            return RedirectToAction("Index", new {eventId = eventEntity.Id});
        }

        [HttpPost]
        [Authorize]
        public ActionResult SaveFromPopup(CreateEditEventViewModel vm)
        {
            TimeSpan span = vm.EndTime.Subtract(vm.StartTime);
            var duration = (int) span.TotalMinutes;

            var eventEntity = _eventService.GetEvent(vm.Id);
            if (!_audienceService.IsFree(vm.AudienceId, vm.StartTime, vm.EndTime, vm.Id) || duration < 20)
            {
                var model = _audienceMapService.GetAudienceMap(AudienceMapSelector.AudienceMapId);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            eventEntity.Title = vm.Title;
            eventEntity.AdditionalInfo = vm.AdditionalInfo;
            eventEntity.AudienceId = vm.AudienceId;
            eventEntity.AuthorName = vm.AuthorName;
            eventEntity.IsAuthorShown = vm.IsAuthorShown;
            eventEntity.IsJoinAvailable = vm.IsJoinAvailable;
            eventEntity.StartTime = vm.StartTime;
            eventEntity.EndTime = vm.EndTime;

            _eventService.UpdateEvent(User, eventEntity);

            return RedirectToAction("DisplayEventPopup", new {eventId = eventEntity.Id});
        }
    }
}

Booking/Booking.Web/Controllers/ScheduleController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using Booking.Repositories;
using Booking.Services.Interfaces;
using Booking.Services.Services;
using Booking.Web.ViewModels.Home;
using Booking.Web.ViewModels.Schedule;

namespace Booking.Web.Controllers
{
    public class ScheduleController : Controller
    {
        private readonly IScheduleService _scheduleService;
        private readonly IAudienceMapService _audienceMapService;
        private readonly IBookingScheduleRuleService _bookingScheduleRuleService;

        public ScheduleController()
        {
            var uof = new UnitOfWork();
            _scheduleService = new ScheduleService(uof.EventRepository);
            _audienceMapService = new AudienceMapService(uof);
            _bookingScheduleRuleService = new BookingScheduleRuleService(uof);
        }

        [HttpGet]
        public ActionResult GetDaySchedule(DateTime date, Guid audienceMapId)
        {
            var rule = _bookingScheduleRuleService.GetRule(date);

            var events = _scheduleService.GetEventsByDay(date, audienceMapId);
            var viewModel = Mapper.Map<DayScheduleViewModel>(events);
            viewModel.BookingHourStart = rule.StartHour;
            viewModel.BookingHourEnd = rule.EndHour;

            var audienceMap = _audienceMapService.GetAudienceMap(audienceMapId);
            var availableAudiences = audienceMap.Audiences.Where(a => a.IsBookingAvailable)
                .Select(a => new ScheduleRowName { Id = a.Id, Name = a.Name });
            viewModel.AvailableAudiences = availableAudiences;

            return Json(viewModel, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetScheduleRule(DateTime date)
        {
            var rule = _bookingScheduleRuleService.GetRule(date);
            var ruleVm = new ScheduleRuleVm
            {
                IsBookingAvailable = _bookingScheduleRuleService.BookingAvailable(rule),
                StartHour = rule.StartHour,
                EndHour = rule.EndHour
            };

            return Json(ruleVm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetNextAvailableDate(DateTime date)
        {
            var next = _bookingScheduleRuleService.GetNextAvailableDate(date);
            var rule = _bookingScheduleRuleService.GetRule(next);
            var vm = new AvailableDayViewModel
            {
                Date = next,
                StartHour = rule.StartHour,
                EndHour = rule.EndHour
            };

            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetPreviousAvailableDate(DateTime date)
        {
            var next = _bookingScheduleRuleService.GetPreviousAvailableDate(date);
            var rule = _bookingScheduleRuleService.GetRule(next);
            var vm = new AvailableDayViewModel
            {
                Date = next,
                StartHour = rule.StartHour,
                EndHour = rule.EndHour
            };

            return Json(vm, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetDisabledDaysForMonth(int month, int year)
        {
            var days = _bookingScheduleRuleService.GetDisabledDaysForMonth(month, year);
            var vm = new DisabledDaysViewModel
            {
                Days = days,
                Month = month,
                Year = year
            };

            return Json(vm, JsonRequestBehavior.AllowGet);
        }
    }
}

Booking/Booking.Web/Views/Shared/_DeletePartial.cshtml
@using Booking.Web.Localization
@model string

@using (Ajax.BeginForm("Delete", "Manage", new {userId = @Model},
    new AjaxOptions
    {
        HttpMethod = "Post",
        OnSuccess = "closeCancelEventPopup"
    }))
{
    @Html.AntiForgeryToken()
    <div class="cancel-event-container">
        <div class="cancel-event-header">
            <i class="fa fa-ban icon-ban" aria-hidden="true"></i>
            <span class="cancel-event-ask-message">@Localization.UserDeleteTitle</span>
        </div>
        <div>@Localization.UserDeleteText</div>
        <div class="btns-body-cancel-popup">
            <button class="close-this-popup" data-dismiss="modal">@Localization.No</button>
            <input type="submit" id="del-event" class="cancel-event-submit" data-id="@Model" value="@Localization.Yes"/>
        </div>
        <input type="hidden" id="delete-event-popup-url" value="@Url.Action("Delete", "Manage")"/>
    </div>
}

Booking/Booking.Web/Views/Shared/_DisplayEventPopup.cshtml
@using Booking.Web.Localization
@using Booking.Web.ViewModels.Event
@model Booking.Web.ViewModels.Event.DisplayEventPopupViewModel

<div id="event-display-popup-@Model.Id" class="event-display-popup">
    <input type="hidden" id="event-page-url" value="@Url.Action("Index", "Event", new {eventId = Model.Id})"/>

    <div class="display-popup-header">
        <div class="event-date">
            <div>@Model.EventDate</div>
            <span>@Model.EventDateTime.ToString("HH:mm") - @Model.EventDateTime.AddMinutes(Model.Duration).ToString("HH:mm")</span>
        </div>
        @if (Model.CanEdit)
        {
            <button class="btn-edit-event">@Localization.Edit</button>
            <button class="btn-cancel-event" id="btn-show-cancel-popup" data-eventId="@Model.Id" onclick="displayCancelEventPopup()" data-toggle="modal" data-target=".example-modal-sm">@Localization.Cancel</button>
        }

        <button class="btn-close-event" id="close-popup-@Model.Id"></button>
    </div>
    <div class="display-popup-body">
        <h4>@Model.Title</h4>
        <div class="form-group">@Model.AdditionalInfo</div>
        <div class="form-group">
            @if (!string.IsNullOrEmpty(Model.AuthorName))
            {
                <i class="fa fa-user" aria-hidden="true"></i>
                <span class="author-name">@Model.AuthorName</span>
            }
            @if (Model.IsJoinAvailable)
            {
                <i class="fa fa-users" aria-hidden="true"></i>
                <span class="participants-count">@Model.ParticipantsEmails.Count</span>
            }
        </div>
        @if (Model.IsJoinAvailable)
        {
            @Html.Partial("_JoinEventPartial", new JoinEventViewModel
            {
                EventId = Model.Id,
                ParticipantsCount = Model.ParticipantsEmails.Count,
                ParticipantsCountLabelHidden = true
            })
        }
        <div class="icons-container">
            <i class="fa fa-calendar-plus-o" aria-hidden="true"></i>
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
            <i class="fa fa-print" aria-hidden="true"></i>
            <i class="fa fa-link" id="btn-event-page-@Model.Id" aria-hidden="true"></i>
        </div>
    </div>

</div>

Booking/Booking.Web/Views/Shared/_HorizontalSchedulePartial.cshtml
@using Booking.Web.Localization
@using Booking.Web.Localization

<input type="hidden" id="get-day-schedule-url" value="@Url.Action("GetDaySchedule", "Schedule")"/>

<div id="main-schedule-container">
    <div id="schedule-control-container">
        <table id="day-header-table" class="table-header-footer">
            <tr>
                <th id="schedule-mode-buttons" class="first-th">
                    <div class="schedule-mode-buttons-container">
                        <i id="schedule-mode-table-only" class="fa fa-align-justify" aria-hidden="true"></i>
                        <i id="schedule-mode-with-calendar" class="fa fa-th-list" aria-hidden="true"></i>
                    </div>
                </th>
                <th id="schedule-day-header" class="second-th">
                    <div>
                        <i id="decrement-date-button" class='fa fa-caret-left caret-arrow' aria-hidden='true'></i>
                        <span id="day-header-title"></span>
                        <i id="increment-date-button" class='fa fa-caret-right caret-arrow' aria-hidden='true'></i>
                    </div>
                </th>
            </tr>
        </table>

        <div id="schedule-table">
            <table id="schedule-rooms-column">
            </table>
            <div id="schedule-viewport-outer">
                <div id="schedule-viewport">
                    <div id="slider-now" class="schedule-slider">
                        <img class="schedule-slider-top" src="@Url.Content("~/Content/Images/schedule/today-top.png")"/>
                        <img class="schedule-slider-bottom" src="@Url.Content("~/Content/Images/schedule/today-bottom.png")"/>
                        <div class="slider-caption">@Localization.Now</div>
                    </div>

                    <div id="slider-draggable" class="schedule-slider">
                        <img class="schedule-slider-top" src="@Url.Content("~/Content/Images/schedule/today-active-top.png")"/>
                        <img class="schedule-slider-bottom" src="@Url.Content("~/Content/Images/schedule/today-active-bottom.png")"/>
                        <div class="slider-caption"></div>
                    </div>
                    <table id="schedule-contents-table">
                    </table>
                </div>
            </div>
        </div>


        <table class="table-header-footer">
            <tr style="height: 22px"></tr>
            <tr>
                <th class="first-th">
                </th>
                <th class="second-th">
                    <span id="btn-goto-now-left" class="btn-goto-now"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> @Localization.Now</span>
                    <span id="btn-goto-now-right" class="btn-goto-now">@Localization.Now <i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
                </th>
            </tr>
        </table>
    </div>

    <div id="datepicker-container">
        <!--<i class='fa fa-caret-left caret-arrow' aria-hidden='true'></i>-->
        <div id="datepicker"></div>
        <!--<i class='fa fa-caret-right caret-arrow' aria-hidden='true'></i>-->
        <div>
            <span id="btn-goto-today-left" class="btn-goto-today"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> @Localization.Today</span>
            <span id="btn-goto-today-right" class="btn-goto-today">@Localization.Today <i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
        </div>
    </div>
</div>

Booking/Booking.Web/Views/Shared/_JoinEventPartial.cshtml
@using Booking.Web.Localization
@model Booking.Web.ViewModels.Event.JoinEventViewModel

@using (Html.BeginForm("Participate", "Event", FormMethod.Post, new
{
    @class = "join-event-form", role = "form",
    id = string.Format("join-event-form-{0}", Model.EventId)
}))
{
    @Html.AntiForgeryToken()

    if (!Model.ParticipantsCountLabelHidden)
    {
        <span>@string.Format(Localization.EventPageParticipantsCount, Model.ParticipantsCount)</span>
        <span style="margin-left: 15px;">@Localization.Join</span>
    }
    <div class="join-event-container">
        @Html.HiddenFor(m => m.EventId)
        @Html.ValidationMessageFor(m => m.Email, "", new {@class = "validation-error"})
        @Html.TextBoxFor(m => m.Email, new {@class = "join-event-form-email", placeholder = Localization.EnterEmailToJoin, autocomplete = "off" })
    </div>
    <i class="fa fa-plus" onclick="joinEvent('@Model.EventId')" aria-hidden="true"></i>
    <input type="submit" value="submit" class="join-event-submit"/>
}

Booking/Booking.Web/Views/Shared/_Layout.cshtml
@using Booking.Web.Localization
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="@Url.Content("~/Content/Images/favicon.ico")" type="image/x-icon">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/Content/datetime-updown.css")
    @Styles.Render("~/Content/new-event-popup.css")
    @Styles.Render("~/Content/edit-event-popup.css")
    @Styles.Render("~/Content/checkbox-styles.css")
    @RenderSection("styles", false)
</head>
<body>
<div id="page-wrapper">
    <header>
        <div class="page-container">
            <div class="navb">
                <ul id="navb" class="navb">
                    <li>
                        <div class="logo-nav-container">
                            <a href="@Url.Action("Index", "Home")">
                                <img src="@Url.Content("~/Content/Images/logo-red.png")"/>
                            </a>
                        </div>
                    </li>
                   
                    
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="@(ViewBag.ActiveLink == "Profile" ? "active" : "")">
                                <a href="@Url.Action("Index", "Profile",new { userId = User.Identity.GetUserId()})">
                                    <i class="fa fa-user" aria-hidden="true"></i> @User.Identity.Name</a>
                            </li>
                        }
                        else
                        {
                            <li class="@(ViewBag.ActiveLink == "Login" ? "active" : "")">
                                @Html.ActionLink(@Localization.Login, "Login", "Account")
                            </li>
                        }
                           
                    <li class="@(ViewBag.ActiveLink == "Contact" ? "active" : "")">
                        @Html.ActionLink(@Localization.Feedback, "Index", "Contact")
                    </li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="@(ViewBag.ActiveLink == "Users" ? "active" : "")">
                            @Html.ActionLink(@Localization.Users, "UserList", "Manage")
                        </li>
                    }
                    <li class="@(ViewBag.ActiveLink == "Index" ? "active" : "")">
                        @Html.ActionLink(@Localization.Schedule, "Index", "Home")
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <i id="btn-new-event-popup" class="fa fa-plus-square" aria-hidden="false" data-toggle="modal" data-target=".bd-example-modal-sm"></i>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </header>

    <div id="page-content">
        @RenderBody()
    </div>

    <footer>
        <div style="text-align: center;">
            <div class="logo-container">
                <img src="@Url.Content("~/Content/Images/logo.png")"/>
            </div>
            <p> @Localization.All_rights_reserved &copy; @DateTime.Now.Year </p>
        </div>

        <ul class="nav navbar-nav" style="font-size:8px">
            <li class="active"><a href="@Url.Action("SelectMap", "Home")">Map selection</a></li>
        </ul>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/Scripts/project/datetime-updown.js")
@Scripts.Render("~/Scripts/project/new-event.js")
@Scripts.Render("~/Scripts/project/popup-scripts.js")
@Scripts.Render("~/Scripts/project/edit-event-popup.js")
@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
@Scripts.Render("//code.jquery.com/ui/1.12.1/jquery-ui.js")
@RenderSection("scripts", false)

<input type="hidden" id="get-new-event-popup-url" value="@Url.Action("GetNewEventPopup", "Event")"/>
<input type="hidden" id="get-schedule-rule-url" value="@Url.Action("GetScheduleRule", "Schedule")"/>
<input type="hidden" id="get-next-available-date-url" value="@Url.Action("GetNextAvailableDate", "Schedule")"/>
<input type="hidden" id="get-previous-available-date-url" value="@Url.Action("GetPreviousAvailableDate", "Schedule")"/>
<input type="hidden" id="get-disabled-days-month-url" value="@Url.Action("GetDisabledDaysForMonth", "Schedule")"/>

<div class="modal fade bd-example-modal-sm" id="CreateEventModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div id="new-event-popup"></div>
    </div>
</div>

<input type="hidden" id="cancel-event-popup-url" value="@Url.Action("GetCancellationForm", "Event")" />

<div class="modal fade example-modal-sm" id="CancelEvent" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div id="cancel-event-popup"></div>
    </div>
</div>

</body>
</html>

Booking/Booking.Web/Views/Shared/_LoginLayout.cshtml
@using Booking.Web.Localization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="@Url.Content("~/Content/Images/favicon.ico")" type="image/x-icon">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/login-layout.css")
    @Styles.Render("~/Content/form-inputs.css")
    @Styles.Render("~/Content/font-awesome/css/font-awesome.min.css")
</head>
<body>
<div class="container-vertical-align">
    <div id="login-container">
        <div id="body-container">
            <div id="title">
                <span>@ViewBag.Title</span>
            </div>
            @RenderBody()
        </div>
        <div id="login-nav-menu">
            <a href="@Url.Action("Index", "Home")">
                <div class="logo-container">
                    <img src="@Url.Content("~/Content/Images/logo.png")"/>
                </div>
            </a>
            <ul>
                <li class="@(ViewBag.ActiveLink == "Login" ? "active" : "")">
                    @Html.ActionLink(@Localization.Login, "Login", "Account")
                </li>
                <li class="@(ViewBag.ActiveLink == "Register" ? "active" : "")">
                    @Html.ActionLink(Localization.Register, "Register", "Account")
                </li>
                <li class="@(ViewBag.ActiveLink == "ResetPassword" ? "active" : "")">
                    @Html.ActionLink(Localization.ResetPassword, "ResetPassword", "Account")
                </li>
            </ul>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
@RenderSection("scripts", required: false)

<script>
    $(document)
        .ready(function() {
            var resizeLoginContainer = function() {
                var w = window.innerWidth;
                var newWidth = w > 1050 ? 0.85 * w : 900;
                document.getElementById("login-container").setAttribute("style", "width:" + newWidth + "px;");
            }

            resizeLoginContainer();

            $(window).on('resize', resizeLoginContainer);
        });
</script>

</body>
</html>

Booking/Booking.Web/Views/Shared/_ResetPasswordPartial.cshtml
@using Booking.Web.Localization;
@model Booking.Web.ViewModels.Profile.ProfileViewModel



    @using (Ajax.BeginForm("ChangePassword", "Manage", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "Post",
        UpdateTargetId = "passwordReplace",
        OnSuccess = "$.validator.unobtrusive.parse('form');"

    }))
    {
        @Html.AntiForgeryToken()
        <H3 style="text-align: center">@Localization.PasswordChange</H3>
                    @Html.ValidationMessageFor(m => m.ChangePasswordForm.OldPassword, "", new { @class = "validation-error" })
                    @Html.PasswordFor(m => m.ChangePasswordForm.OldPassword, new { @class = "profile-input", placeholder = @Localization.PasswordOld, @id = "oldPassword", })

                    @Html.ValidationMessageFor(m => m.ChangePasswordForm.NewPassword, "", new { @class = "validation-error" })
                    @Html.PasswordFor(m => m.ChangePasswordForm.NewPassword, new { @class = "profile-input", placeholder = @Localization.PasswordNew, @id = "newPassword", })

                    @Html.ValidationMessageFor(m => m.ChangePasswordForm.ConfirmPassword, "", new { @class = "validation-error" })
                    @Html.PasswordFor(m => m.ChangePasswordForm.ConfirmPassword, new { @class = "profile-input", placeholder = @Localization.PasswordNewRepeat, @id = "confirmNewPassword", })

                    <input type="submit" value=@Localization.Save class="profile-submit" />

        if (ViewData["PasswordSuccess"] != null)
        {
            <div style="margin: 0px auto; text-align:center">
                <i class="fa fa-check-circle" style="font-size: 30px; text-align: center" aria-hidden="true"></i><span>@Localization.PasswordSuccess</span>
            </div>
        }
        if (ViewData["PasswordFaild"] != null)
        {
            <span>@Localization.PasswordError</span>
        }
    }